name: DI_DEPLOY_ON_PUSH

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    #environment: TEST
    steps:
      - uses: actions/checkout@v2
      - name: Unzip VCTL
        run: |
          unzip tool/vctl.zip
      - name: Build zipped solution from Vflow folder and Manifest.json
        run: |
          mkdir temp_solution/content/files -p
          cp -r vflow temp_solution/content/files/vflow
          cp manifest.json temp_solution/manifest.json
          cd temp_solution
          zip -r ../solution.zip . *
          cd ..
      - name: VCTL Login
        run: |
          chmod +x tool/vctl
          ./vctl login ${{ secrets.DI_HOST }} ${{ secrets.DI_TENANT }} ${{ secrets.DI_USER }} -p '${{ secrets.DI_PASSWORD }}'     
      - name: VCTL Upload Solution to Solution Repository
        run: |
          ./vctl solution delete "$(jq -r .name manifest.json)" "$(jq -r .version manifest.json)" || echo "No Solution deleted"
          ./vctl solution upload "solution.zip"
      - name: VCTL Delete old Files in Dirs
        run: |
          ./vctl vrep user rm /files/vflow/subengines/com/sap/python36/operators --recursive
          ./vctl vrep user rm /files/vflow/graphs --recursive
      - name: VCTL Import Solution in User Workspace
        run: ./vctl vrep user import-solution "$(jq -r .name manifest.json)" "$(jq -r .version manifest.json)"
      - name: VCTL Logout
        run: ./vctl logout
