# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: TEST
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
#       - name: Setup tmate session
#         uses: mxschmitt/action-tmate@v3

      - name: VCTL test
        run: |
          
          pwd
          solution_version=$(jq -r .version manifest.json)
          solution_name=$(jq -r .name manifest.json)
          ls
          chmod +x tool/vctl
          ./tool/vctl login ${{ secrets.DI_HOST }} ${{ secrets.DI_TENANT }} ${{ secrets.DI_USER }} -p '${{ secrets.DI_PASSWORD }}'
          mkdir temp_solution/content/files -p
          pwd
          ls
          cp -r vflow temp_solution/content/files/vflow
          cp manifest.json temp_solution/manifest.json
          cd temp_solution
          zip -r ../solution-${solution_version}.zip . *
          cd ..
          ./tool/vctl solution upload "solution-${solution_version}.zip"

          ./tool/vctl vrep user rm /files/vflow/subengines/com/sap/python36/operators --recursive
          ./tool/vctl vrep user rm /files/vflow/graphs --recursive

          ./tool/vctl vrep user import-solution "${solution_name}" "${solution_version}"

          ./tool/vctl logout

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
